### ISSUE TITLE
楼主有结论吗？

### ISSUE THREAD

**Issue by ByteRax** [yndjl/DPITest#1]
RT

非常感谢

**Comment by yndjl** [comment]
测试过，方案基本还是可行的，而且原有项目迁移成本低。原理就是修改了应用绘制页面时的density值来达到适配（可以使用横向或纵向适配）

**Comment by ByteRax** [comment]
谢谢，😘

**Comment by yndjl** [comment]
小哥哥，试过之后觉得可行，可以给个小星星哦:stuck_out_tongue_winking_eye:。过段时间我在整理整理这个项目
